name: Build Full-Stack Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'addOnDemoClient/**'
      - 'addOnDemoServer/**'
      - '.github/workflows/master-docker-hub-arm.yml'
      - 'Dockerfile'
      - 'nginx/**'

env:
  DOCKERHUB_USERNAME: lin77777
  IMAGE_NAME: addondemo-fullstack
  VERSION: v1.0

jobs:
  build:
    name: Build Full-Stack Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: . # 表示构建镜像时使用当前的目录，与构建相关的所有文件都会从当前目录去找
        platforms: linux/arm/v7,linux/amd64
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_ENV=production